services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    container_name: radash_api
    depends_on:
    - database
    - redis
    environment:
    - NODE_ENV=${NODE_ENV}
    - RADIUS_SECRET=${RADIUS_SECRET}
    - TIMEZONE_IANA=${TIMEZONE_IANA}
    - TIMEZONE=${TIMEZONE}
    - DATABASE_HOST=database
    - DATABASE_PORT=3306
    - DATABASE_USER=${MYSQL_USER}
    - DATABASE_PASSWORD=${MYSQL_PASSWORD}
    - DATABASE_NAME=${MYSQL_DATABASE}
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - EMAIL_ADDRESS=${EMAIL_ADDRESS}
    - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    - EMAIL_HOST=${EMAIL_HOST}
    - EMAIL_PORT=${EMAIL_PORT}
    - AFRICAS_TALKING_API_KEY=${AFRICAS_TALKING_API_KEY}
    - AFRICAS_TALKING_USERNAME=${AFRICAS_TALKING_USERNAME}
    - AFRICAS_TALKING_SENDER_ID=${AFRICAS_TALKING_SENDER_ID}
    - MPESA_CONSUMER_KEY=${MPESA_CONSUMER_KEY}
    - MPESA_SECRET_KEY=${MPESA_SECRET_KEY}
    - MPESA_PAYBILL=${MPESA_PAYBILL}
    - MPESA_PASSKEY=${MPESA_PASSKEY}
    - JWT_SECRET=${JWT_SECRET}
    - DASHBOARD_API_KEY=${DASHBOARD_API_KEY}
    - DASHBOARD_URL=${DASHBOARD_URL}
    image: node:alpine
    ports:
    - 3009:3009
    restart: always
    volumes:
    - ./api:/usr/src/app
    - /usr/src/app/node_modules
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    container_name: radash_dashboard
    depends_on:
    - api
    environment:
    - NODE_ENV=${NODE_ENV}
    - NEXT_PUBLIC_API_URL=http://api:3009
    - API_KEY=${DASHBOARD_API_KEY}
    - NEXTAUTH_SECRET=${JWT_SECRET}
    - NEXTAUTH_URL=${DASHBOARD_URL}
    image: node:alpine
    ports:
    - 3000:3000
    restart: always
    volumes:
    - ./dashboard:/app
    - /app/node_modules
  database:
    container_name: radash_database
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    image: mysql
    restart: always
    volumes:
    - ./mysql_data:/var/lib/mysql
  radius_reload:
    build:
      context: ./radius_reload
      dockerfile: Dockerfile
    container_name: radash_reload
    depends_on:
    - database
    environment:
    - DATABASE_HOST=database
    - DATABASE_PORT=3306
    - DATABASE_USER=${MYSQL_USER}
    - DATABASE_PASSWORD=${MYSQL_PASSWORD}
    - DATABASE_NAME=${MYSQL_DATABASE}
    image: python:alpine
    restart: always
    volumes:
    - ./radius_reload:/app
  redis:
    container_name: radash_redis
    image: redis:alpine
    ports:
    - 6379:6379
    restart: always
